[project]
name = "uv-monorerpo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sdk",
]

[tool.uv.sources]
sdk = { path = "libs/sdk", editable = true }


